import "./globals.css";

import { Press_Start_2P } from 'next/font/google';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pressStart2P = Press_Start_2P({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={ pressStart2P.className}
      >
        {children}
      </body>
    </html>
  );
}
